GET http://192.168.1.80:8000/api/getGroups
Accept: */*
Cache-Control: no-cache
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1NDI3MzEwNTEsImV4cCI6MTU0MjczNDY1MSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiY29tYmF0YW50ZWtAZ21haWwuY29tIn0.rztkcfmSqrwF2u1EahZAyoi8BgIJDe1etGs9mzd1CnGjEYeJZVzwk3tRuDbhY53ZTLvRm3DzTDY2C1GO5uyFG8Lh0ozJ33RUQ3mH4c8NzU9W7n91-00xlQg41Renh7FfTuUuu5E4HGK6ft21NvDVBQTptv0qRzuCK07Qhnfx10b_Q0l9WXRnJVOh9Q0eSQYmo4agdYnY0SYphwUJsVubpWqZPLKIMQtPTQMGmn4Yp9Z9xIWoc7oy1C-_L6zm-HsiyvIA5s5TMZiIOdTRr0pI3YXJU3ChBM3C390amvKmi097nNkm2SnTKUE-en8bvQ2XAft86EzUOFJ-gHTfIbHO36dthArpoalbR7deeiORkFcWHHC0LBPmukLV46h2GThFndl1t25V8zACjbBfcYNBcySairLqc8DIeGu3qEzDkU9DXWBgU9KNq-mp_Uwt4KWX21sJ5qPUy_KL0Et1QNhMab72zJTRjrT8n8K7HxQX5HjmKxsj-VycTst5PYV4NENi4SBWC30ogEpMdA_ADtNyssxKodP71nMYyzlbpe8f4Ict_d3AV41t8gAulsdzjjmoX24AxAlbADytwWsdkMhS0YC_TU7M1XoNTteiAK_r5JjUjAAnD0PhgtwKKyD5xIGX2KD9oTqNdb1QkEFNcDbFfYdahwjqEqFS3-ZPTmv2bCk

###

