login:
    path: /login
    controller: App\Controller\OperatorController::login

signUp:
    path: /signUp
    controller: App\Controller\OperatorController::signUp

getGroups:
    path: /getGroups
    controller: App\Controller\PrimaryController::getGroups

getClients:
    path: /getClients
    controller: App\Controller\PrimaryController::getClients