<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT251Qat\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT251Qat/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerT251Qat.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerT251Qat\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerT251Qat\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'T251Qat',
    'container.build_id' => '52c55340',
    'container.build_time' => 1542736978,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerT251Qat');
